export const onboardingQuestions = [
    { id: 'q1', text: 'What is the name of your business?' },
    { id: 'q2', text: 'Briefly describe what your business sells.' },
    { id: 'q3', text: 'What are your business hours?' },
    { id: 'q4', text: 'What is your business address?' },
    { id: 'q5', text: 'What is the price range of your products/services?' },
    { id: 'q6', text: 'How can a customer purchase from you? (e.g., website, in-store, delivery)' },
    { id: 'q7', text: 'Do you offer any discounts for new customers?' },
    { id: 'q8', text: 'What is your return policy?' },
    { id: 'q9', text: 'What are the main features of your best-selling product?' },
    { id: 'q10', text: 'Who is your ideal customer?' },
    { id: 'q11', text: 'What makes your business unique compared to competitors?' },
    { id: 'q12', text: 'What payment methods do you accept?' },
    { id: 'q13', text: 'Do you have a website or social media page?' },
    { id: 'q14', text: 'What is your shipping policy and cost?' },
    { id: 'q15', text: 'How long does shipping usually take?' },
    { id: 'q16', text: 'Are there any warranties on your products?' },
    { id: 'q17', text: 'What should the AI do if it cannot answer a question?' },
    { id: 'q18', text: 'What is the tone the AI should use? (e.g., formal, friendly, humorous)' },
    { id: 'q19', text: 'Are there any specific words or phrases the AI should avoid?' },
    { id: 'q20', text: 'Provide a sample successful sales conversation.' },
]; 