version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: deepchat_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: deepchat123
      MONGO_INITDB_DATABASE: deepchat
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    networks:
      - deepchat-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: deepchat_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass deepchat123
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - deepchat-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: deepchat_backend
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:deepchat123@mongodb:27017/deepchat?authSource=admin
      - REDIS_URL=redis://:deepchat123@redis:6379
      - JWT_SECRET=mario-super-secret-key-production-2024
      - JWT_EXPIRES_IN=7d
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ZARINPAL_MERCHANT_ID=${ZARINPAL_MERCHANT_ID}
      - ZARINPAL_CALLBACK_URL=${ZARINPAL_CALLBACK_URL}
      - AGENT_URL=http://agent:3002
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./apps/backend/uploads:/app/uploads
      - ./apps/backend/logs:/app/logs
    ports:
      - "5000:5000"
    networks:
      - deepchat-network

  # AI Agent Service
  agent:
    build:
      context: .
      dockerfile: apps/agent/Dockerfile
    container_name: deepchat_agent
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=production
      - AGENT_PORT=3002
      - MONGODB_URI=mongodb://admin:deepchat123@mongodb:27017/deepchat?authSource=admin
      - REDIS_URL=redis://:deepchat123@redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
    volumes:
      - ./apps/agent/logs:/app/logs
    ports:
      - "3002:3002"
    networks:
      - deepchat-network

  # Frontend Next.js
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: deepchat_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:5000
      - NEXT_PUBLIC_ENABLE_AI_FEATURES=true
      - NEXT_PUBLIC_ENABLE_CHAT_HISTORY=true
      - NEXT_PUBLIC_ENABLE_ANALYTICS=false
    volumes:
      - ./apps/frontend/public/sounds:/app/public/sounds
    ports:
      - "3000:3000"
    networks:
      - deepchat-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: deepchat_nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/frontend/public:/var/www/html/public:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - deepchat-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  deepchat-network:
    driver: bridge